name: 'Create GitHub Deployment'
description: 'Create a GitHub deployment and set it to in_progress status'

inputs:
  github-token:
    description: 'GitHub token for API access'
    required: true
  repository:
    description: 'Repository in owner/repo format'
    required: true
  sha:
    description: 'Git SHA to deploy'
    required: true
  environment:
    description: 'Environment name for the deployment'
    required: true
  description:
    description: 'Description for the deployment'
    required: false
    default: ''
  initial-status-description:
    description: 'Description for the initial in_progress status'
    required: false
    default: 'Deployment in progress...'

outputs:
  deployment-id:
    description: 'The ID of the created deployment'
    value: ${{ steps.create-deployment.outputs.deployment_id }}

runs:
  using: composite
  steps:
    - name: Create deployment
      id: create-deployment
      shell: bash
      run: |
        DEPLOYMENT_ID=$(cat << EOF | gh api repos/${{ inputs.repository }}/deployments --input - --jq '.id'
        {
          "ref": "${{ inputs.sha }}",
          "environment": "${{ inputs.environment }}",
          "description": "${{ inputs.description }}",
          "auto_merge": false,
          "required_contexts": []
        }
        EOF
        )
        echo "deployment_id=$DEPLOYMENT_ID" >> $GITHUB_OUTPUT
        
        gh api repos/${{ inputs.repository }}/deployments/$DEPLOYMENT_ID/statuses \
          -f state=in_progress \
          -f description="${{ inputs.initial-status-description }}"
      env:
        GH_TOKEN: ${{ inputs.github-token }}
